<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>psc</string>
		<string>pscode</string>
	</array>
	<key>name</key>
	<string>pseudo-code</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(tableau_de( [0-9]*)? caractere)\b</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//(.*)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"(?:\\.|[^"\\])*\"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'(?:\\.|[^'\\]){1}\'</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>('\\u[0-9]{4}')</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(vrai|faux)\b</string>
			<key>name</key>
			<string>constant.boolean</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(constante)\b</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\))</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>keyword.control.endline</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(algorithme|debut|fin)\b</string>
			<key>name</key>
			<string>keyword.control.algorithm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(si|sinon|sinon_si|fsi)\b</string>
			<key>name</key>
			<string>keyword.control.condition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(choix_sur|cas|fchoix|entre)\b</string>
			<key>name</key>
			<string>keyword.control.choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(afficher|saisir|ligne_suivante)\b</string>
			<key>name</key>
			<string>keyword.control.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(declarer|taille|allonger|redimensionner)\b</string>
			<key>name</key>
			<string>keyword.control.memory</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(modulo|rand)\b</string>
			<key>name</key>
			<string>keyword.control.maths</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ET|ET_ALORS|OU|OU_SINON)\b</string>
			<key>name</key>
			<string>keyword.operator.binary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(NON)\b</string>
			<key>name</key>
			<string>keyword.operator.unary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(vaut|ne_vaut_pas)\b</string>
			<key>name</key>
			<string>keyword.operator.identity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.?)(-?)([0-9]+)(e?)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;-|&gt;=|&lt;=|&gt;|&lt;|\+|-|/|\*)</string>
			<key>name</key>
			<string>keyword.operator.binary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(booleen|reel|entier|entier_naturel|caractere)\b</string>
			<key>name</key>
			<string>support.type.primitive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(tableau_de|string)\b</string>
			<key>name</key>
			<string>support.type.complex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pseudo-code</string>
	<key>uuid</key>
	<string>9b70ed3b-a554-42f5-b736-ecd13dc00b36</string>
</dict>
</plist>
