<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>psc</string>
		<string>pscode</string>
	</array>
	<key>name</key>
	<string>pseudo-code</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(si|sinon|sinon si|fsi)\b</string>
			<key>name</key>
			<string>string.other.quoted-or-unquoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ET|ET_ALORS|OU|OU_SINON)\b</string>
			<key>name</key>
			<string>constant.language.binary_logical_operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(vaut|ne_vaut_pas)\b</string>
			<key>name</key>
			<string>constant.language.binary_identity_operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NOT)\b</string>
			<key>name</key>
			<string>constant.language.logical_operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NOT)\b</string>
			<key>name</key>
			<string>constant.language.logical_operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((?-)[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pseudo-code</string>
	<key>uuid</key>
	<string>9b70ed3b-a554-42f5-b736-ecd13dc00b36</string>
</dict>
</plist>
